BEGIN;

CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    cpf VARCHAR(50) NOT NULL UNIQUE,
    secret VARCHAR(200) NOT NULL,
    balance INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
