ALTER TABLE account
ALTER COLUMN id TYPE VARCHAR(50);

ALTER TABLE transfer
ALTER COLUMN id TYPE VARCHAR(50),
ALTER COLUMN account_origin_id TYPE VARCHAR(50),
ALTER COLUMN account_destination_id TYPE VARCHAR(50);
