// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package transfer

import (
	"context"
	"github.com/thalissonfelipe/banking/banking/domain/entity"
	"github.com/thalissonfelipe/banking/banking/domain/usecases"
	"github.com/thalissonfelipe/banking/banking/domain/vos"
	"sync"
)

// UsecaseMock is a mock implementation of usecases.Transfer.
//
// 	func TestSomethingThatUsesTransfer(t *testing.T) {
//
// 		// make and configure a mocked usecases.Transfer
// 		mockedTransfer := &UsecaseMock{
// 			ListTransfersFunc: func(contextMoqParam context.Context, accountID vos.AccountID) ([]entity.Transfer, error) {
// 				panic("mock out the ListTransfers method")
// 			},
// 			PerformTransferFunc: func(contextMoqParam context.Context, performTransferInput usecases.PerformTransferInput) error {
// 				panic("mock out the PerformTransfer method")
// 			},
// 		}
//
// 		// use mockedTransfer in code that requires usecases.Transfer
// 		// and then make assertions.
//
// 	}
type UsecaseMock struct {
	// ListTransfersFunc mocks the ListTransfers method.
	ListTransfersFunc func(contextMoqParam context.Context, accountID vos.AccountID) ([]entity.Transfer, error)

	// PerformTransferFunc mocks the PerformTransfer method.
	PerformTransferFunc func(contextMoqParam context.Context, performTransferInput usecases.PerformTransferInput) error

	// calls tracks calls to the methods.
	calls struct {
		// ListTransfers holds details about calls to the ListTransfers method.
		ListTransfers []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// AccountID is the accountID argument value.
			AccountID vos.AccountID
		}
		// PerformTransfer holds details about calls to the PerformTransfer method.
		PerformTransfer []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// PerformTransferInput is the performTransferInput argument value.
			PerformTransferInput usecases.PerformTransferInput
		}
	}
	lockListTransfers   sync.RWMutex
	lockPerformTransfer sync.RWMutex
}

// ListTransfers calls ListTransfersFunc.
func (mock *UsecaseMock) ListTransfers(contextMoqParam context.Context, accountID vos.AccountID) ([]entity.Transfer, error) {
	if mock.ListTransfersFunc == nil {
		panic("UsecaseMock.ListTransfersFunc: method is nil but Transfer.ListTransfers was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		AccountID       vos.AccountID
	}{
		ContextMoqParam: contextMoqParam,
		AccountID:       accountID,
	}
	mock.lockListTransfers.Lock()
	mock.calls.ListTransfers = append(mock.calls.ListTransfers, callInfo)
	mock.lockListTransfers.Unlock()
	return mock.ListTransfersFunc(contextMoqParam, accountID)
}

// ListTransfersCalls gets all the calls that were made to ListTransfers.
// Check the length with:
//     len(mockedTransfer.ListTransfersCalls())
func (mock *UsecaseMock) ListTransfersCalls() []struct {
	ContextMoqParam context.Context
	AccountID       vos.AccountID
} {
	var calls []struct {
		ContextMoqParam context.Context
		AccountID       vos.AccountID
	}
	mock.lockListTransfers.RLock()
	calls = mock.calls.ListTransfers
	mock.lockListTransfers.RUnlock()
	return calls
}

// PerformTransfer calls PerformTransferFunc.
func (mock *UsecaseMock) PerformTransfer(contextMoqParam context.Context, performTransferInput usecases.PerformTransferInput) error {
	if mock.PerformTransferFunc == nil {
		panic("UsecaseMock.PerformTransferFunc: method is nil but Transfer.PerformTransfer was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		PerformTransferInput usecases.PerformTransferInput
	}{
		ContextMoqParam:      contextMoqParam,
		PerformTransferInput: performTransferInput,
	}
	mock.lockPerformTransfer.Lock()
	mock.calls.PerformTransfer = append(mock.calls.PerformTransfer, callInfo)
	mock.lockPerformTransfer.Unlock()
	return mock.PerformTransferFunc(contextMoqParam, performTransferInput)
}

// PerformTransferCalls gets all the calls that were made to PerformTransfer.
// Check the length with:
//     len(mockedTransfer.PerformTransferCalls())
func (mock *UsecaseMock) PerformTransferCalls() []struct {
	ContextMoqParam      context.Context
	PerformTransferInput usecases.PerformTransferInput
} {
	var calls []struct {
		ContextMoqParam      context.Context
		PerformTransferInput usecases.PerformTransferInput
	}
	mock.lockPerformTransfer.RLock()
	calls = mock.calls.PerformTransfer
	mock.lockPerformTransfer.RUnlock()
	return calls
}
