name: Test
on:
  - pull_request

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Set color
      id: random-color-generator
      run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

    - name: Get color
      run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
  
    - name: Comment on PR  
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}
          })
