name: Test
on:
  - pull_request

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --exclude '*' --include 'go.mod'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
